#!/bin/bash
#--------------------------------------------------------
#   Don't remove this section for credits
#   Don't rename this file
#--------------------------------------------------------
#   This script is used for setting up
#   Xderm-Mini GUI for OpenWrt by ryanfauzi1
#   Installation script by helmiau a.k.a Helmi Amirudin
#   my profile page https://me.helmiau.my.id
#   my github https://github.com/helmiau
#--------------------------------------------------------

#-- Warna Teks Installer
RED='\033[0;31m' # Merah
GRE='\033[1;32m' # Hijau Muda
YEL='\033[1;33m' # Kuning
NOR='\033[0;37m' # Abu Abu Normal
BLU='\033[1;34m' # Biru Muda

#-- Xderm Old Version Code
v10="9385a88730f47ce476e91a94b5f598e1a8b5b112"
v11="5fd6ba4b365e4e4689f963abb92710d8d7ea6ea0"
v12="edf57728fb9aaf95565a79b219e6f1ac0ad107c6"
v13="031e146ef48ed53aa9d4a2646d4a86ac52be0ac0"
v14="543e78f91ef7549c8324783f949345aed14c36b8"
v15="e306e3b26b6a81cf0b7315a9caf2b815e1880033"
v16="61bf52e2c77f31910a870b9346870f234df0793a"
v17="5f8a7c2e3fd329e5519e0e2a3356cad44bb525cf"
v18="ddaa9bd2bec4a71dd62cb9d03cfc31b80e3723cc"
v19="3343be6f696ae6eb56c9ad337f6439739705a966"
v20="b4880ccd8aae1bf11369696009c49c3f3a3ebdad"
v21="e21fd6847abc99a7e1b8a67745ebbfa3bd74f96d"
v22="b397d0993f4eef1b39785d75a10309b00bca61b9"
v23="4ff1d4bbdf5196deea5c11480484fc6cb2195938"
v24="eb882e93acdbe4fc622e56761e22f6d524a61951"
v25="2284a420bb991709e8015893c7eff796bbbd2ab7"
v26="57baee0f87c97db38fc4796c9822cb957023fa96"
v27="99808960f82bcd5f469b1a35887485faeb182ada"
v28="2b7a2c8a82941f3d894102105c007dd7414599ab"
v29="f5a2294f22fcb9855f1f008820383edf6effd93e"
v30="d7e233bb8769540238c1e06ec0c3d3f7047ec003"
#-- Uneditable Info for script checking purpose

#-- Uneditable Info for script checking purpose
INSTALLERNAME="$(basename "$0")"
CHECKNET="http://github.com/ryanfauzi1/xderm-mini_GUI"
XDERMPATH="/www/xderm"
XDERMPATHBAK="/www/xdermbak"
XDERMCONFIGBAK="/www/xderm-config"
XDERMINFO="/www/xderm/xderm-mini"
XDERMPATHINFO=$(if [ -d ${XDERMPATH} ]; then echo -e "${GRE}Available"; else echo -e "${RED}Unavailable"; fi)
XDERMPATHBAKINFO=$(if [ -d ${XDERMCONFIGBAK} ]; then echo -e "${GRE}Available"; else echo -e "${RED}Unavailable"; fi)
INSTALLSTAT=$(if [ -f "${XDERMINFO}" ]; then echo -e "${GRE}Installed"; else echo -e "${RED}Not Installed"; fi)
GREPXDERMVER=$(grep "Copyr" "${XDERMINFO}" | awk "NR==4" | awk '{print $6}')
XDERMVER=$(if [[ $GREPXDERMVER =~ [0-9] ]]; then echo -e " ~ v$GREPXDERMVER"; else echo -e ""; fi)
if [ -f /root/auth.txt ]; then
	USERNOW=$(grep user /root/auth.txt | sed 's/.*user=//')
	PASSNOW=$(grep passwd /root/auth.txt | sed 's/.*passwd=//')
else
	USERNOW="${RED}auth file not exist"
	PASSNOW="${RED}auth file not exist"
fi
LOGINOW=$(if [ -e /www/xderm/login.php ]; then echo -e "${GRE}Available"; else echo -e "${RED}Unavailable"; fi)
LOGINOWBAK=$(if [ -e /www/xderm/login.php.xdrtool ]; then echo -e "${GRE}Available"; else echo -e "${RED}Unavailable"; fi)
URL="https://raw.githubusercontent.com/ryanfauzi1/xderm-mini_GUI/main"
OLDURL="https://raw.githubusercontent.com/ryanfauzi1/xderm-mini_GUI/"
SCRIPTVER="4.1"
#-- Installer Scripts
echo -e "${NOR}==========================================="
echo -e "     ${RED}Xderm ${BLU}Mini ${YEL}Tools ${NOR}v$SCRIPTVER ${GRE}by helmiau${NOR}"
echo "==========================================="
echo -e "  ${GRE}Xderm Binary    : $INSTALLSTAT$XDERMVER"
echo -e "  ${GRE}Xderm Path      : $XDERMPATHINFO"
echo -e "  ${GRE}Xderm Backup    : $XDERMPATHBAKINFO${NOR}"
echo "==========================================="
echo -e "  ${YEL}Panel Username  : $USERNOW"
echo -e "  ${YEL}Panel Password  : $PASSNOW"
echo -e "  ${YEL}Login Page      : $LOGINOW"
echo -e "  ${YEL}Login Pg Backup : $LOGINOWBAK${NOR}"
echo "==========================================="
echo -e "               ${YEL}Command Lists${NOR}"
echo -e "===========================================${GRE}"
echo "     Install Xderm Mini       : 1"
echo "     Install Theme by Agus S  : 2"
echo "     Update Xderm Mini        : 3"
echo "     Fix index.php            : 4"
echo "     Change User & Pass Login : 5"
echo "     Change Username Only     : 6"
echo "     Change Password Only     : 7"
echo "     Install Login Page       : 8"
echo "     Remove Login Page        : 9"
echo "     Install Older Version    : 10"
echo "     Remove Xderm Mini Files  : 11"
echo -e "${NOR}==========================================="
echo -e "  ${BLU}Available Older Version  : v1.0 ~ v3.0"
echo -e "    ${BLU}type 10 for v1.0, 20 for v2.0, etc"
echo -e "${NOR}==========================================="
echo -e "           ${YEL}Exit = type anything !${NOR}"
echo "==========================================="
echo ""
echo -n "   Enter Your Option : " 
read -r jawab
echo "==========================================="

# wget -S --spider github.com/squarepants96/xdrtheme-adminlte 2>&1 #Network Checker

function xderm_checknet() {
	echo "  Checking connections..."
	if wget -S --spider "$CHECKNET" 2>&1 | grep -q 'HTTP/1.1 200 OK'; then
		echo "  Internet connected..."
	else
		echo "  No internet connection or repository url unavailable..."
		echo "  Leaving."
		sleep 3
		clear
		./"$INSTALLERNAME"
	fi
}

function xderm_install() {
	clear
	echo "######################################"
	echo " Installer Xderm Mini GUI Latest Version"
	echo "######################################"
	echo "Installing latest version of Xderm Mini GUI, please wait....."
	echo "Creating required directories....."
	mkdir -p "$XDERMPATH" "$XDERMPATH"/js "$XDERMPATH"/img "$XDERMPATH"/log
	echo "Downloading files....."
	wget -O "$XDERMPATH"/index.php $URL/index.php -q
	echo "Index php downloaded....."
	wget -O "$XDERMPATH"/index.html $URL/index.html -q
	echo "Index html downloaded....."
	wget -O "$XDERMPATH"/xderm-mini $URL/xderm-mini -q
	echo "Xderm Mini binary downloaded....."
	wget -O "$XDERMPATH"/login.php $URL/login.php -q
	echo "Index php downloaded....."
	wget -O "$XDERMPATH"/header.php $URL/header.php -q
	echo "Header panel downloaded....."
	wget -O "$XDERMPATH"/config.txt $URL/config.txt -q
	echo "Config file downloaded....."
	wget -O "$XDERMPATH"/js/jquery-2.1.3.min.js $URL/jquery-2.1.3.min.js -q
	echo "Jquery downloaded....."
	wget -O "$XDERMPATH"/img/image.png $URL/image.png -q
	echo "Logo downloaded....."
	wget -O "$XDERMPATH"/img/fav.ico $URL/fav.ico -q
	echo "Panel icon downloaded....."
	wget -O "$XDERMPATH"/img/ico.png $URL/ico.png -q
	echo "Icon downloaded....."
	wget -O "$XDERMPATH"/img/background.jpg $URL/background.jpg -q
	echo "Background downloaded....."
	wget -O "$XDERMPATH"/xdrtheme-blue-agus $URL/adds/xdrtheme-blue-agus -q
	echo "Info downloaded....."
	wget -O /bin/xdrauth $URL/adds/xdrauth -q
	chmod +x /bin/xdrauth
	echo "Authorization terminal tool downloaded....."
	wget -O /bin/xdrtool $URL/adds/xdrtool -q
	chmod +x /bin/xdrtool
	echo "Xderm Mini Tool downloaded....."
	if [ -f $(cat "$XDERMPATH"/log/st 2>/dev/null) ]; then
		echo "Starting Xderm Binary....."
		echo Start > "$XDERMPATH"/log/st
	fi
	echo -e "user=admin\npasswd=xderm" > /root/auth.txt
	echo -e "xderm-mini GUI terinstall.\n\nSilahkan Akses 'http://192.168.1.1/xderm'"
	echo -e "Default Authentication\nUsername: admin\nPassword: xderm\n"
	echo -e "Untuk mengganti User dan Password, silahkan edit /root/auth.txt"
	echo -e "Atau jalankan command terminal xdrauth untuk mengubahnya"
	echo "Jangan lupa setting config dulu di webui nya."
	echo "Terima kasih -salam ryan fauzi."
}

function xderm_update() {
	echo "==========================================="
	echo -e " Installing manual update..."
	wget -O $XDERMPATH/xderm-mini $URL/xderm-mini -q
	wget -O $XDERMPATH/index.php $URL/index.php -q
	echo "==========================================="
	echo -e " Manual update installation done..."
	echo "==========================================="
}

function xderm_old_install() {
	clear
	echo -n "  Enter older version for install (type 10~30) : "
	read -r VER
	VERSI=$(grep v$VER $INSTALLERNAME | awk -F'"' '$0=$2')
	echo "######################################"
	echo -e "   Older Xderm Mini GUI Installer $VER"
	echo "######################################"
	URLOLD="$OLDURL$VERSI"
	echo -e "Installing Xderm Mini GUI v$VER, please wait....."
	# echo "$URLOLD"
	echo "Creating required directories....."
	mkdir -p "$XDERMPATH" "$XDERMPATH"/js "$XDERMPATH"/img "$XDERMPATH"/log
	echo "Downloading files....."
	wget -O "$XDERMPATH"/index.php $URLOLD/index.php -q
	echo "Index php downloaded....."
	wget -O "$XDERMPATH"/index.html $URLOLD/index.html -q
	echo "Index html downloaded....."
	wget -O "$XDERMPATH"/xderm-mini $URLOLD/xderm-mini -q
	echo "Xderm Mini binary downloaded....."
	wget -O "$XDERMPATH"/login.php $URLOLD/login.php -q
	echo "Index php downloaded....."
	wget -O "$XDERMPATH"/header.php $URLOLD/header.php -q
	echo "Header panel downloaded....."
	wget -O "$XDERMPATH"/config.txt $URLOLD/config.txt -q
	echo "Config file downloaded....."
	wget -O "$XDERMPATH"/js/jquery-2.1.3.min.js $URLOLD/jquery-2.1.3.min.js -q
	echo "Jquery downloaded....."
	wget -O "$XDERMPATH"/img/image.png $URLOLD/image.png -q
	echo "Logo downloaded....."
	wget -O "$XDERMPATH"/img/fav.ico $URLOLD/fav.ico -q
	echo "Panel icon downloaded....."
	wget -O "$XDERMPATH"/img/ico.png $URLOLD/ico.png -q
	echo "Icon downloaded....."
	wget -O "$XDERMPATH"/img/background.jpg $URLOLD/background.jpg -q
	echo "Background downloaded....."
	wget -O "$XDERMPATH"/xdrtheme-blue-agus $URL/adds/xdrtheme-blue-agus -q
	echo "Info downloaded....."
	wget -O /bin/xdrauth $URL/adds/xdrauth -q
	chmod +x /bin/xdrauth
	echo "Authorization terminal tool downloaded....."
	wget -O /bin/xdrtool $URL/adds/xdrtool -q
	chmod +x /bin/xdrtool
	echo "Xderm Mini Tool downloaded....."
	if [ -f $(cat "$XDERMPATH"/log/st 2>/dev/null) ]; then
		echo "Starting Xderm Binary....."
		echo Start > "$XDERMPATH"/log/st
	fi
	echo -e "user=admin\npasswd=xderm" > /root/auth.txt
	echo -e "xderm-mini GUI terinstall.\n\nSilahkan Akses 'http://192.168.1.1/xderm'"
	echo -e "Default Authentication\nUsername: admin\nPassword: xderm\n"
	echo -e "Untuk mengganti User dan Password, silahkan edit /root/auth.txt"
	echo -e "Atau jalankan command terminal xdrauth untuk mengubahnya"
	echo "Jangan lupa setting config dulu di webui nya."
	echo "Terima kasih -salam ryan fauzi."
}

function xderm_uninstall() {
	echo "  Removing Xderm Mini..."
	sleep 1
	if [[ -d $XDERMPATH ]]; then
		rm -rf $XDERMPATH
		echo "  Xderm Mini uninstalled..."
	else
		echo "  $XDERMPATH is not available..."
		echo "  Leaving ..."	
	fi
}

function xderm_config_backup() {
	echo "  Backing up Xderm Mini configurations..."
	if [[ ! -d $XDERMCONFIGBAK ]]; then
		echo "  Backup directory is not available, creating..."
		mkdir $XDERMCONFIGBAK
		echo "  Backup directory created..."
	else
		echo "  Backup directory available, skipping..."			
	fi
	if [[ -d $XDERMPATH/config ]]; then
		cp $XDERMPATH/config $XDERMCONFIGBAK/configbak
		echo "  Config folder backed up..."
	else
		echo "  Config folder is not available, skipping..."			
	fi
	if [[ -f $XDERMPATH/config.txt ]]; then
		cp $XDERMPATH/config.txt $XDERMCONFIGBAK/config.txt.bak
		echo "  Config file backed up..."
	else
		echo "  Config file is not available, skipping..."			
	fi
	if [[ -f /root/auth.txt ]]; then
		cp /root/auth.txt $XDERMCONFIGBAK/auth.txt
		echo "  Login panel auth backed up..."
	else
		echo "  Login panel auth is not available, skipping..."			
	fi
}

function xderm_config_restore() {
	echo "  Restoring Xderm Mini configurations..."
	if [[ -d $XDERMCONFIGBAK/configbak ]]; then
		cp $XDERMCONFIGBAK/configbak $XDERMPATH/config
		echo "  Configs folder restored..."
	else
		echo "  Config folder is not available, skipping..."			
	fi
	if [[ -f $XDERMCONFIGBAK/config.txt.bak ]]; then
		cp $XDERMCONFIGBAK/config.txt.bak $XDERMPATH/config.txt
		echo "  Config file restored..."
	else
		echo "  Config file is not available, skipping..."			
	fi
	if [[ -f $XDERMCONFIGBAK/auth.txt ]]; then
		cp $XDERMCONFIGBAK/auth.txt /root/auth.txt
		echo "  Login panel auth restored..."
	else
		echo "  Login panel auth is not available, skipping..."			
	fi
	echo "  Backing up Xderm Mini configurations..."
	if [[ -d $XDERMCONFIGBAK ]]; then
		echo "  Backup directory is available, deleting..."
		rm -rf $XDERMCONFIGBAK
		echo "  Backup directory deleted..."
	else
		echo "  Backup directory not available, skipping..."			
	fi
}

function xderm_start() {
	echo "  Starting Xderm Mini..."
	echo Start > $XDERMPATH/log/st
	echo "  Xderm Mini Started..."
	echo "  Done ! Refresh Xderm Mini Page"
}

function xderm_stop() {
	echo "  Stopping Xderm Mini..."
	echo Stop > $XDERMPATH/log/st
	echo "  Xderm Mini Stopped..."
	echo "  Done ! Refresh Xderm Mini Page"
}

function xderm_install_theme() {
	echo "==========================================="
	echo -e " Installing Default Theme by Agus Sriawan"
	echo "==========================================="
	mkdir -p "$XDERMPATH" "$XDERMPATH"/js "$XDERMPATH"/img "$XDERMPATH"/log
	wget -O "$XDERMPATH"/index.php $URL/index.php -q
	wget -O "$XDERMPATH"/index.html $URL/index.html -q
	wget -O "$XDERMPATH"/xderm-mini $URL/xderm-mini -q
	wget -O "$XDERMPATH"/login.php $URL/login.php -q
	wget -O "$XDERMPATH"/header.php $URL/header.php -q
	wget -O "$XDERMPATH"/config.txt $URL/config.txt -q
	wget -O "$XDERMPATH"/js/jquery-2.1.3.min.js $URL/jquery-2.1.3.min.js -q
	wget -O "$XDERMPATH"/img/image.png $URL/image.png -q
	wget -O "$XDERMPATH"/img/fav.ico $URL/fav.ico -q
	wget -O "$XDERMPATH"/img/ico.png $URL/ico.png -q
	wget -O "$XDERMPATH"/img/background.jpg $URL/background.jpg -q
	echo "==========================================="
	echo -e " Installation finished !"
	echo "==========================================="
}

function xderm_change_auth() {
	echo -n "  Enter New Username : " 
	read -r USERNEW
	echo "==========================================="
	echo -n "  Enter New Password : " 
	read -r PASSNEW
	echo -e "user=$USERNEW\npasswd=$PASSNEW" > /root/auth.txt
}

function xderm_change_user() {
	echo -n "  Enter New Username : " 
	read -r USERNEW
	echo -e "user=$USERNEW\npasswd=$PASSNOW" > /root/auth.txt
}

function xderm_change_pass() {
	echo -n "  Enter New Password : "
	read -r PASSNEW
	echo -e "user=$USERNOW\npasswd=$PASSNEW" > /root/auth.txt
}

function xderm_remove_login() {
	echo "==========================================="
	echo -e "     Xderm Mini Login Page Remover by helmiau "
	echo "==========================================="
	echo -e " "
	echo -e "Notes : "
	echo -e "- This script will remove xderm-mini login page"
	echo -e "- Please clear all web history and cache after removal!"
	echo -e "- If bug occured, Open incognito tab"
	echo -e "- If bug still occured, Use other browser"
	echo -e ""
	echo -e " Process starting after 2 secs....."
	sleep 2
	echo -e " Removal process started..."
	sleep 1
	echo -e ""

	echo -e " Finding login.php file..."
	nyari=$(find "$XDERMPATH")
	if [[ $nyari == *"login.php"* ]]; then
		mv "$XDERMPATH"/login.php "$XDERMPATH"/login.php.xdrtool
		echo -e " login.php file deleted !"
		sleep 1
	else
		echo -e " Removal failed ! because login.php file is unavailable"
		sleep 1
	fi

	echo -e " Finding header.php file..."
	nyari=$(find "$XDERMPATH")
	if [[ $nyari == *"header.php"* ]]; then
		mv "$XDERMPATH"/header.php "$XDERMPATH"/header.php.xdrtool
		echo -e " header.php file deleted !"
		sleep 1
	else
		echo -e " Removal failed ! because login.php file is unavailable"
		sleep 1
	fi

	echo "==========================================="
	echo -e " Removal login page process finished..."
}

function xderm_install_login() {
	echo "==========================================="
	echo -e "     Xderm Mini Login Page Installer by helmiau "
	echo "==========================================="
	echo -e " "
	echo -e "Notes : "
	echo -e "- This script will install xderm-mini login page"
	echo -e "- Please clear all web history and cache after removal!"
	echo -e "- If bug occured, Open incognito tab"
	echo -e "- If bug still occured, Use other browser"
	echo -e ""
	echo -e " Process starting after 2 secs....."
	sleep 2
	echo -e " Install process started..."
	sleep 1
	echo -e ""

	echo -e " Finding login.php file..."
	nyari=$(find "$XDERMPATH")
	if [[ $nyari == *"login.php.xdrtool"* ]]; then
		mv "$XDERMPATH"/login.php.xdrtool "$XDERMPATH"/login.php
		echo -e " login.php file installed !"
		sleep 1
	else
		echo -e " Install failed ! because login.php backup file is unavailable"
		echo -e " Try online installation"
		wget -O "$XDERMPATH"/login.php "$URLTHEME"/login.php -q
		sleep 1
	fi

	echo -e " Finding header.php file..."
	nyari=$(find "$XDERMPATH")
	if [[ $nyari == *"header.php.xdrtool"* ]]; then
		mv "$XDERMPATH"/header.php.xdrtool "$XDERMPATH"/header.php
		echo -e " header.php file installed !"
		sleep 1
	else
		echo -e " Install failed ! because header.php backup file is unavailable"
		echo -e " Try online installation"
		wget -O "$XDERMPATH"/header.php "$URLTHEME"/header.php -q
		sleep 1
	fi

	echo "==========================================="
	echo -e " Install login page process finished..."
}

function xderm_fixphp() {
	echo "==========================================="
	echo -e "  Download index.php fixer by helmiau "
	echo "==========================================="
	echo -e " "
	echo -e "Notes : "
	echo -e "- This tool will fix xderm-mini and libernet web ui page"
	echo -e "- If bug fixed words appeared, it's mean bug fixed"
	echo -e "- Reboot your device manually after fixing"
	sleep 2
	echo -e " "
	echo -e "If bug still appear after reboot, do these :"
	echo -e "- Clear all web history and cache"
	echo -e "- Open incognito tab"
	echo -e "- Use other browser"
	echo -e ""
	echo -e " Fixing process started !..."
	sleep 2
	echo -e ""
	echo -e " Fixing bug..."
	sleep 2
	echo -e ""

	helmiooo=$(cat /etc/config/uhttpd)
	if [[ $helmiooo == *"uhttpd 'mai"* ]]; then
	echo -e "Step 1 done ! Resuming to step 2..."
	sleep 1
	sed -i "/config uhttpd 'main'/a list interpreter '.php=/usr/bin/php-cgi'" /etc/config/uhttpd
	fi

	helmiooo=$(cat /etc/config/uhttpd)
	if [[ $helmiooo == *"uhttpd 'mai"* ]]; then
	echo -e "Step 2 done ! Resuming to step 3..."
	sleep 1
	sed -i "/config uhttpd 'main'/a option ubus_prefix '/ubus'" /etc/config/uhttpd
	fi

	helmiooo=$(cat /etc/config/uhttpd)
	if [[ $helmiooo == *"uhttpd mai"* ]]; then
	echo -e "Step 3 done ! Resuming to last step..."
	sleep 1
	sed -i "/config uhttpd main/a list interpreter '.php=/usr/bin/php-cgi'" /etc/config/uhttpd
	fi

	helmiooo=$(cat /etc/config/uhttpd)
	if [[ $helmiooo == *"uhttpd mai"* ]]; then
	echo -e "Everything has been done..."
	sleep 1
	sed -i "/config uhttpd main/a option ubus_prefix '/ubus'" /etc/config/uhttpd

	fi


	echo "==========================================="
	echo -e " Removal process finished..!"
	echo -e " Please reboot your device !"
	echo "==========================================="
}

#-- Install Xderm Mini
if [[ $jawab == "up" || $jawab == "UP" || $jawab == "1" ]]; then
	xderm_checknet \ &&
	xderm_config_backup \ &&
	xderm_install \ &&
	xderm_config_restore \ &&
	echo "==========================================="
	clear
	./"$INSTALLERNAME"

#-- Install Agus theme
elif [[ $jawab == "2" ]]; then
	xderm_checknet \ &&
	xderm_config_backup \ &&
	xderm_install_theme \ &&
	xderm_config_restore \ &&
	echo "==========================================="
	clear
	./"$INSTALLERNAME"

#-- Update Xderm
elif [[ $jawab == "3" ]]; then
	xderm_checknet \ &&
	xderm_config_backup \ &&
	xderm_update \ &&
	xderm_config_restore \ &&
	echo "==========================================="
	clear
	./"$INSTALLERNAME"

#-- Fix Index
elif [[ $jawab == "4" ]]; then
	xderm_install_login \ &&
	echo "==========================================="
	clear
	./"$INSTALLERNAME"

#-- Change auth
elif [[ $jawab == "5" ]]; then
	xderm_change_auth \ &&
	echo "==========================================="
	clear
	./"$INSTALLERNAME"

#-- Change user
elif [[ $jawab == "6" ]]; then
	xderm_change_user \ &&
	echo "==========================================="
	clear
	./"$INSTALLERNAME"

#-- Change pass
elif [[ $jawab == "7" ]]; then
	xderm_change_pass \ &&
	echo "==========================================="
	clear
	./"$INSTALLERNAME"

#-- Install login page
elif [[ $jawab == "8" ]]; then
	xderm_install_login \ &&
	echo "==========================================="
	clear
	./"$INSTALLERNAME"

#-- Remove login page
elif [[ $jawab == "9" ]]; then
	xderm_remove_login \ &&
	echo "==========================================="
	clear
	./"$INSTALLERNAME"

#-- Old version installer
elif [[ $jawab == "10" ]]; then
	xderm_checknet \ &&
	xderm_config_backup \ &&
	xderm_uninstall \ &&
	xderm_old_install \ &&
	xderm_config_restore \ &&
	echo "==========================================="
	clear
	./"$INSTALLERNAME"

#-- Clean/remove xderm mini
elif [[ $jawab == "10" ]]; then
	xderm_uninstall \ &&
	echo "==========================================="
	clear
	./"$INSTALLERNAME"

#-- Exit program
else
	echo "    Exiting program !"
	echo "==========================================="
	exit
fi

#
#   This script is used to install Xderm Mini GUI custom theme
#   Installation script by helmiau a.k.a Helmi Amirudin
#   my profile page https://me.helmiau.my.id
#   my github https://github.com/helmiau
#
